app = 'protoimsg-nllb'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  HOST = '::'
  PORT = '6060'
  OMP_NUM_THREADS = '1'

# Internal-only service â€” Fly needs this to route private network traffic
[http_service]
  internal_port = 6060
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[checks]
  [checks.health]
    port = 6060
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "15m"
    path = "/health"

[mounts]
  source = 'nllb_models'
  destination = '/models'

[[vm]]
  memory = '8gb'
  cpu_kind = 'performance'
  cpus = 2
