app = 'protoimsg-nllb'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  HOST = '::'
  PORT = '6060'
  OMP_NUM_THREADS = '1'

# This ensures it is NOT reachable via protoimsg-nllb.fly.dev.
[[services]]
  internal_port = 6060
  protocol = "tcp"

  [[services.ports]]
    port = 443
    protocol = "tcp"
    [services.ports.tls_options]
      alpn = ['h2']
    [services.ports.http_options]
      h2_backend = true

# This allows the internal load balancer to speak HTTP/2 (gRPC) to your container
  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
      interval = "15s"
      timeout = "2s"
      grace_period = "15m" # Keep this high for the initial model conversion

[mounts]
  source = 'nllb_models'
  destination = '/models'

[[vm]]
  memory = '8gb'
  cpu_kind = 'performance'
  cpus = 2
