app = 'protoimsg-libretranslate-staging'
primary_region = 'iad'

[build]
  image = 'libretranslate/libretranslate:latest'

[env]
  LT_LOAD_ONLY = 'en,es,ru,ar,uk,ga'
  LT_DISABLE_WEB_UI = 'true'
  LT_UPDATE_MODELS = 'true'
  LT_THREADS = '4'

[mounts]
  source = 'lt_models'
  destination = '/home/libretranslate/.local'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2

[checks]
  [checks.health]
    port = 5000
    type = 'http'
    interval = '15s'
    timeout = '10s'
    grace_period = '600s'
    path = '/languages'

[[vm]]
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 2
